version: "3"

services:
  mongo:
    container_name: mongodb_${CONTAINER_NAME}
    image: mongo:latest
    restart: always
    ports:
      - 127.0.0.1:${MONGODB_PORT:-27018}:${MONGODB_PORT:-27018}
    volumes:
      - ${MONGODB_PATH:-./mongodb}:/data/db
    # TODO: add auth

  2p3_telegram_bot:
    container_name: ${CONTAINER_NAME}
    command: python3 bot/bot.py
    restart: always
    build:
      context: "."
      dockerfile: Dockerfile
    depends_on:
      - mongo

  mongo_express:
    container_name: mongo-express_${CONTAINER_NAME}
    image: mongo-express:latest
    restart: always
    ports:
      - 127.0.0.1:${MONGO_EXPRESS_PORT:-8088}:${MONGO_EXPRESS_PORT:-8088}
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=${MONGODB_PORT:-27018}
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=false
      - ME_CONFIG_MONGODB_AUTH_DATABASE=${CONTAINER_NAME}
      - ME_CONFIG_BASICAUTH_USERNAME=${MONGO_EXPRESS_USERNAME:-username}
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGO_EXPRESS_PASSWORD:-password}
    depends_on:
      - mongo
